source 'http://rubygems.org'

# Build and include the LL gem from the parent directory
gem "lapis_lazuli", path: './../'


# Project specific gems
gem 'cucumber', '~> 4'
gem 'xml-simple'
gem 'mechanize'
gem 'simplecov'
gem 'test-unit'
