################################################################################
# Copyright <%= config[:year] %> spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version <%= config[:lapis_lazuli][:version] %>
# Author: "<%= config[:user] %>" <<%= config[:email] %>>

# interactions_steps.rb is used to interact with elements on the page.

Given(/^the user navigates to (.*?) in (.*?)$/) do |site, language|
  # Combine the configuration depth with dots
  config_name = "#{site.downcase}.#{language.downcase}"
  # Get the value of the configuration (see /config/config.yml)
  url         = env(config_name)
  # Go to the URL
  browser.goto url
end

Given(/^the user searches for "(.*?)"$/) do |query|
  # Get the input element
  searchbox = browser.find(:text_field => {:name => "q"})
  # Make sure the input field is empty
  searchbox.clear rescue log.debug "Could not clear searchbox"
  # Fill in the query
  searchbox.send_keys(query)
  # Press enter to submit the search
  searchbox.send_keys(:enter)
end

When(/^the user clicks on link "(.*?)"$/) do |url|
  # Search for the element that includes the expected text
  browser.wait(
    :like => {
      :element   => :a,
      :attribute => :href,
      :include   => url
    }
  ).click
end