################################################################################
# Copyright <%= config[:year] %> spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version <%= config[:lapis_lazuli][:version] %>
# Author: "<%= config[:user] %>" <<%= config[:email] %>>

# precondition_steps.rb is used to define steps that contain multiple steps to come to a certain start of a scenrario.
# For example: "Given the user is logged in" will contain all steps done before logging in

Given(/^the user has searched for "(.*?)" on (.*?) in (.*)$/) do |query, site, language|
  # Run step to go to page
  step "the user navigates to #{site} in #{language}"
  # Run step to search
  step "the user searches for \"#{query}\""
end