################################################################################
# Copyright <%= config[:year] %> spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version <%= config[:lapis_lazuli][:version] %>
# Author: "<%= config[:user] %>" <<%= config[:email] %>>
require 'lapis_lazuli'
require 'lapis_lazuli/cucumber'

LapisLazuli.config_file = "config/config.yml"
World(LapisLazuli)

# Transition function from old codebase to new
load 'features/support/transition.rb'
