################################################################################
# Copyright 2014 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 0.0.1
# Author: "spriteCloud" <info@spritecloud.com>
require 'lapis_lazuli'
require 'lapis_lazuli/cucumber'

module TestModule
  def test_func
    # does nothing. being able to call it is important
  end
end

LapisLazuli::WorldModule::Config.config_file = "config/config.yml"
World(LapisLazuli, TestModule)

LapisLazuli.Start do
  # Print gem information
  print "---- VERSION INFO ----\n"
  print "Lapis Lazuli: #{Gem.loaded_specs['lapis_lazuli'].version}\n"
  print "Selenium webdriver: #{Gem.loaded_specs['selenium-webdriver'].version}\n"
  print "Watir: #{Gem.loaded_specs['watir'].version}\n"
  print "---- VERSION INFO ----\n\n"
end

LapisLazuli::WorldModule::Browser.browser_module(TestModule)

# Transition function from old codebase to new
load 'server/start.rb'

