################################################################################
# Copyright 2014 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 0.0.1
# Author: "Onno Steenbergen" <onno@steenbe.nl>
require 'lapis_lazuli'
require 'lapis_lazuli/cucumber'

LapisLazuli::WorldModule::Config.config_file = "config/config.yml"
World(LapisLazuli)

# Transition function from old codebase to new
load 'server/start.rb'
