################################################################################
# Copyright 2014 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 0.0.1
# Author: "spriteCloud" <info@spritecloud.com>
require 'lapis_lazuli'
require 'lapis_lazuli/cucumber'

module TestModule
  def test_func
    # does nothing. being able to call it is important
  end
end

LapisLazuli::WorldModule::Config.config_file = "config/config.yml"
World(LapisLazuli, TestModule)

LapisLazuli::WorldModule::Driver.driver_module(TestModule)


# Transition function from old codebase to new
load 'server/start.rb'
